[generator]
entrypoint = "generator.py:generate"
owned_outputs = [
  "common/culture/traditions/zz_ant_agot_vanilla_balance_traditions.txt",
  "common/modifiers/zz_ant_agot_vanilla_balance_modifiers.txt",
  "common/men_at_arms_types/zz_ant_agot_vanilla_balance_maa.txt",
  "common/buildings/zz_ant_agot_vanilla_balance_common_buildings.txt",
  "common/buildings/zz_ant_agot_vanilla_balance_duchy_buildings.txt",
]

[[sources]]
name = "any-new-traditions"
kind = "workshop"
item_id = "3241130652"

[[sources]]
name = "any-new-traditions-agot"
kind = "workshop"
item_id = "3371298408"
