load_mod = {
	label = "AGOT"
	workshop_id = "2962333032"
}

load_mod = {
	label = "aGoT: Mayham"
	workshop_id = "3352171144"
}

load_mod = {
	label = "AGOT - Armies of Westeros"
	workshop_id = "2966543745"
}
