[generator]
entrypoint = "implementation.py:generate"
owned_outputs = [
  "common/on_action/agot_on_actions/agot_game_start.txt",
]

[[sources]]
name = "workshop-2962333032"
kind = "workshop"
item_id = "2962333032"

[[sources]]
name = "workshop-3403938445"
kind = "workshop"
item_id = "3403938445"

[[sources]]
name = "workshop-3719888822"
kind = "workshop"
item_id = "3719888822"
