#!/usr/bin/env python3
"""Generate the AGOT excommunication balance overrides."""

from __future__ import annotations

from gen import GenerationContext
from gen.text import (
    definition_span,
    newline_style,
    normalize_newlines,
    read_source,
    replace_exact,
    strip_trailing_whitespace,
)

REQUEST_INTERACTION = "request_excommunication_interaction"
HEAD_INTERACTION = "excommunicate_interaction"

# The request path is the one a vassal or peer initiates, and the religious head
# answers it with an acceptance roll. AGOT's base leaves the roll winnable on
# opinion alone; the override keeps the path usable while requiring a hook, the
# target's sins, or a strongly favourable opinion to carry it.
AGOT_REQUEST_BASE = -50
PATCHED_REQUEST_BASE = -75

# The head-of-faith path has no acceptance roll at all -- AGOT keeps vanilla's
# `auto_accept = yes` -- so the AI cadence and the will-do roll are the only
# levers on how often a religious head excommunicates unprompted.
AGOT_HEAD_FREQUENCY = """\
\tai_frequency_by_tier = {
\t\tbarony = 0
\t\tcounty = 72
\t\tduchy = 36
\t\tkingdom = 12
\t\tempire = 12
\t\thegemony = 12
\t}
"""
PATCHED_HEAD_FREQUENCY = """\
\tai_frequency_by_tier = {
\t\tbarony = 0
\t\tcounty = 0
\t\tduchy = 120
\t\tkingdom = 60
\t\tempire = 60
\t\thegemony = 60
\t}
"""

PATCHED_HEAD_KINGDOM_CADENCE = 60

AGOT_HEAD_BASE = 50
PATCHED_HEAD_BASE = 10

AGOT_HEAD_VENGEFULNESS = "0.5"
PATCHED_HEAD_VENGEFULNESS = "0.25"

# AGOT lets any rivalry qualify. A rivalry is common and the interaction's own
# `on_accept` seeds one, so excommunication compounds itself; the override
# narrows the gate to the two relationships that describe an irreconcilable
# enemy.
AGOT_HEAD_TARGET_GATE = """\
\t\tmodifier = {
\t\t\tfactor = 0
\t\t\tscope:recipient = {
\t\t\t\tNOR = {
\t\t\t\t\thas_relation_rival = scope:actor
\t\t\t\t\thas_relation_nemesis = scope:actor
\t\t\t\t\tis_at_war_with = scope:actor
\t\t\t\t}
\t\t\t}
\t\t}
"""
PATCHED_HEAD_TARGET_GATE = """\
\t\tmodifier = {
\t\t\tfactor = 0
\t\t\tscope:recipient = {
\t\t\t\tNOR = {
\t\t\t\t\thas_relation_nemesis = scope:actor
\t\t\t\t\tis_at_war_with = scope:actor
\t\t\t\t}
\t\t\t}
\t\t}
"""

HEADER = """\
# Generated by workspace/agot_excommunication_balance. Redefines only the two
# excommunication interactions so a religious head excommunicates rarely and
# unprompted requests need real justification. Must load after A Game of
# Thrones.
"""


def build_request_interaction(source: str) -> str:
    """Raise the acceptance bar on the requested-excommunication path."""
    start, end = definition_span(source, REQUEST_INTERACTION)
    interaction = source[start:end]
    return replace_exact(
        interaction,
        f"\t\tbase = {AGOT_REQUEST_BASE}\n",
        f"\t\tbase = {PATCHED_REQUEST_BASE}\n",
        f"{REQUEST_INTERACTION} ai_accept base",
    )


def build_head_interaction(source: str) -> str:
    """Slow and narrow the religious head's own excommunication."""
    start, end = definition_span(source, HEAD_INTERACTION)
    interaction = source[start:end]
    interaction = replace_exact(
        interaction,
        AGOT_HEAD_FREQUENCY,
        PATCHED_HEAD_FREQUENCY,
        f"{HEAD_INTERACTION} ai_frequency_by_tier",
    )
    interaction = replace_exact(
        interaction,
        f"\t\tbase = {AGOT_HEAD_BASE}\n",
        f"\t\tbase = {PATCHED_HEAD_BASE}\n",
        f"{HEAD_INTERACTION} ai_will_do base",
    )
    interaction = replace_exact(
        interaction,
        f"\t\t\tai_vengefulness = {AGOT_HEAD_VENGEFULNESS}\n",
        f"\t\t\tai_vengefulness = {PATCHED_HEAD_VENGEFULNESS}\n",
        f"{HEAD_INTERACTION} ai_will_do vengefulness weight",
    )
    return replace_exact(
        interaction,
        AGOT_HEAD_TARGET_GATE,
        PATCHED_HEAD_TARGET_GATE,
        f"{HEAD_INTERACTION} ai_will_do target gate",
    )


def generate(context: GenerationContext) -> None:
    source_path = context.source("agot-religious-interactions")
    output_path = context.output_path(
        "common/character_interactions/zz_agot_excommunication_balance.txt"
    )

    source_raw = read_source(source_path)
    source = normalize_newlines(source_raw, "\n")

    head = build_head_interaction(source)
    request = build_request_interaction(source)
    output = f"{HEADER}\n{head}\n{request}\n"
    output = normalize_newlines(
        strip_trailing_whitespace(output), newline_style(source_raw)
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8-sig", newline="")
    print(
        f"Generated {HEAD_INTERACTION} (ai_will_do base {PATCHED_HEAD_BASE}, "
        f"kingdom cadence {PATCHED_HEAD_KINGDOM_CADENCE} months) and "
        f"{REQUEST_INTERACTION} (ai_accept base {PATCHED_REQUEST_BASE})."
    )
