#!/usr/bin/env python3
"""Generate the AGOT excommunication-request acceptance override."""

from __future__ import annotations

from pathlib import Path

from gen import GenerationContext
from gen.text import (
    definition_span,
    newline_style,
    normalize_newlines,
    read_source,
    replace_exact,
    strip_trailing_whitespace,
)

INTERACTION = "request_excommunication_interaction"
AGOT_BASE_ACCEPTANCE = -50
PATCHED_BASE_ACCEPTANCE = -100

HEADER = """\
# Generated by workspace/agot_excommunication_balance. Redefines only
# request_excommunication_interaction so religious heads require stronger
# justification before accepting a request. Must load after A Game of Thrones.
"""


def build_interaction(source: str) -> str:
    start, end = definition_span(source, INTERACTION)
    interaction = source[start:end]
    interaction = replace_exact(
        interaction,
        f"\t\tbase = {AGOT_BASE_ACCEPTANCE}\n",
        f"\t\tbase = {PATCHED_BASE_ACCEPTANCE}\n",
        f"{INTERACTION} ai_accept base",
    )
    return f"{HEADER}\n{interaction}\n"


def generate(context: GenerationContext) -> None:
    source_path = context.source("agot-religious-interactions")
    output_path = context.output_path(
        "common/character_interactions/zz_agot_excommunication_balance.txt"
    )

    source_raw = read_source(source_path)
    source = normalize_newlines(source_raw, "\n")
    output = build_interaction(source)
    output = normalize_newlines(
        strip_trailing_whitespace(output), newline_style(source_raw)
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8-sig", newline="")
    print(
        "Generated request_excommunication_interaction with ai_accept base "
        f"{PATCHED_BASE_ACCEPTANCE}."
    )
