load_mod = {
	label = "AGOT"
	workshop_id = "2962333032"
}

load_mod = {
	label = "Legacy of Valyria"
	workshop_id = "3403938445"
}

load_mod = {
	label = "LoV AGOT 0.5.1 bridge"
	workshop_id = "3719888822"
}

load_mod = {
	label = "LoV bridge CK3 1.19 runtime rebase"
	modfile = "../../mods/legacy_of_valyria_bridge_runtime_rebase/descriptor.mod"
}

load_mod = {
	label = "Essos Expanded"
	workshop_id = "3682802751"
}

load_mod = {
	label = "Further East EEP"
	workshop_id = "3768149491"
}
