load_mod = {
	label = "AGOT"
	workshop_id = "2962333032"
}
load_mod = {
	label = "NOW"
	workshop_id = "3664900993"
}
load_mod = {
	label = "NOW CK3 1.19 rebase"
	modfile = "../agot_now_119_rebase/descriptor.mod"
}
load_mod = {
	label = "LoV"
	workshop_id = "3403938445"
}
load_mod = {
	label = "LoV AGOT 0.4.39 RC71"
	modfile = "../../.ignored/CK3_workshop/3719888822/descriptor.mod"
}
load_mod = {
	label = "LoV RC71 CK3 1.19 runtime rebase"
	modfile = "../legacy_of_valyria_039_runtime_rebase/descriptor.mod"
}
load_mod = {
	label = "Essos Expanded"
	workshop_id = "3682802751"
}
load_mod = {
	label = "Essos Expanded LoV history rebase"
	modfile = "../essos_expanded_119_rebase/descriptor.mod"
}
load_mod = {
	label = "Essos Expanded LoV"
	modfile = "../../.ignored/CK3_workshop/3768149491/descriptor.mod"
}
load_mod = {
	label = "NOW + LoV + EE map compatch"
	modfile = "../agot_now_lov_ee_map_compatch/descriptor.mod"
}
load_mod = {
	label = "NOW + LoV + EE world data"
	modfile = "../agot_now_lov_ee_world_data/descriptor.mod"
}
