#!/usr/bin/env python3
"""Generate the keyed redefinitions that protect characters from random death.

Two definitions live in `common/`, which resolves per key by ASCIIbetical
filename, so both are emitted into `zzzz_` files that win the key without
shadowing the neighbouring definitions their source files also carry.

The remaining sources are assertion-only: they pin the upstream markers this
module's runtime behaviour depends on, so a parent that renames or reworks one
fails generation instead of quietly disabling protection.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from gen import GenerationContext
from gen.text import (
    definition_span,
    newline_style,
    normalize_newlines,
    read_source,
    replace_exact,
    strip_trailing_whitespace,
)

# The population gate in common/scripted_triggers/agot_ce_triggers.txt reads
# this modifier. If EZ Mode renames it, every protected character silently
# stops being protected.
CANON_CHILDREN_MODIFIER = "canon_children_easy_mode_health_boost_modifier"

# Holding this flag keeps the battlefield duel from being offered. Every mod
# that defines mfb_commander_duel_event gates its is_valid on the flag's
# absence; agot_ce_apply_protection_effect relies on all of them doing so.
DUEL_COOLDOWN_GATE = "NOT = { has_character_flag = mfb_duel_cooldown }"

DUEL_SOURCES = (
    "battle-events-phase-events",
    "battle-events-agot-phase-events",
    "duels-blademasters-phase-events",
)

COMMANDER_HEADER = """\
# Generated by workspace/agot_canon_enforcement. Redefines AGOT's commander_killed so
# a protected character cannot be picked as the commander who dies in a battle.
# Everything else about the event is AGOT's own. Must sort after every other
# combat_phase_events file, which is what the zzzz_ prefix buys.
"""

DISASTER_HEADER = """\
# Generated by workspace/agot_canon_enforcement. Redefines the natural disaster death
# roll so protected characters are never collected into killable_characters.
# The rest of the effect, including army damage and the player notifications,
# is unchanged. Must sort after every other scripted_effects file.
"""

COMMANDER_GATE = "\tis_valid = {\n\t\texists = root\n"
COMMANDER_GUARD = (
    "\tis_valid = {\n"
    "\t\texists = root\n"
    "\t\t#AGOT Canon Enforcement: protected characters are not eligible victims.\n"
    "\t\tagot_ce_battle_protected_trigger = no\n"
)

TOURNAMENT_HEADER = """\
# Generated by workspace/agot_canon_enforcement. Redefines the tournament
# accident death so a protected contestant survives the melee. The activity log
# entries and the reactions of the other attendees are unchanged. Must sort
# after every other scripted_effects file.
"""

# The two victim deaths in the accident effect, one with a killer and one
# without. Guarding the effect covers every event that calls it, which is what
# reaches both the melee accident and the tourney ground accident.
TOURNAMENT_DEATHS = (
    (
        "\t\t\tscope:accident_victim = {\n"
        "\t\t\t\tdeath = {\n"
        "\t\t\t\t\tdeath_reason = death_contest_melee_accident\n"
        "\t\t\t\t\tkiller = scope:accident_killer\n"
        "\t\t\t\t}\n"
        "\t\t\t}\n",
        "\t\t\tscope:accident_victim = {\n"
        "\t\t\t\tif = {\n"
        "\t\t\t\t\tlimit = { agot_ce_event_death_protected_trigger = no }\n"
        "\t\t\t\t\tdeath = {\n"
        "\t\t\t\t\t\tdeath_reason = death_contest_melee_accident\n"
        "\t\t\t\t\t\tkiller = scope:accident_killer\n"
        "\t\t\t\t\t}\n"
        "\t\t\t\t}\n"
        "\t\t\t}\n",
        "tournament accident death with a killer",
    ),
    (
        "\t\t\tscope:accident_victim = {\n"
        "\t\t\t\tdeath = { death_reason = death_contest_melee_accident }\n"
        "\t\t\t}\n",
        "\t\t\tscope:accident_victim = {\n"
        "\t\t\t\tif = {\n"
        "\t\t\t\t\tlimit = { agot_ce_event_death_protected_trigger = no }\n"
        "\t\t\t\t\tdeath = { death_reason = death_contest_melee_accident }\n"
        "\t\t\t\t}\n"
        "\t\t\t}\n",
        "tournament accident death without a killer",
    ),
)

DISASTER_COLLECT = (
    "\t\t\tevery_character_in_location = { add_to_list = killable_characters }\n"
)
DISASTER_GUARD = (
    "\t\t\tevery_character_in_location = {\n"
    "\t\t\t\t#AGOT Canon Enforcement: protected characters are not collected.\n"
    "\t\t\t\tlimit = { agot_ce_event_death_protected_trigger = no }\n"
    "\t\t\t\tadd_to_list = killable_characters\n"
    "\t\t\t}\n"
)


@dataclass(frozen=True, slots=True)
class RunInputs:
    COMMANDER_PHASE_EVENTS: Path
    NATURAL_DISASTER_EFFECTS: Path
    TOURNAMENT_EFFECTS: Path
    CANON_CHILDREN_MODIFIERS: Path
    DUEL_PHASE_EVENTS: tuple[tuple[str, Path], ...]
    COMMANDER_OUTPUT: Path
    DISASTER_OUTPUT: Path
    TOURNAMENT_OUTPUT: Path


def extract(text: str, name: str) -> str:
    start, end = definition_span(text, name)
    return text[start:end]


def assert_contains(text: str, needle: str, label: str) -> None:
    if needle not in text:
        raise ValueError(f"{label}: expected to find `{needle}`, and it is gone")


def build_commander_killed(text: str) -> str:
    event = replace_exact(
        extract(text, "commander_killed"),
        COMMANDER_GATE,
        COMMANDER_GUARD,
        "commander_killed protected-character gate",
    )
    return f"{COMMANDER_HEADER}\n{event}\n"


def build_natural_disaster(text: str) -> str:
    effect = replace_exact(
        extract(text, "natural_disaster_death_damage_roll_effect"),
        DISASTER_COLLECT,
        DISASTER_GUARD,
        "natural disaster killable_characters collection",
    )
    return f"{DISASTER_HEADER}\n{effect}\n"


def build_tournament_accident(text: str) -> str:
    effect = extract(text, "tournament_accidental_death_effect")
    for old, new, label in TOURNAMENT_DEATHS:
        effect = replace_exact(effect, old, new, label)
    return f"{TOURNAMENT_HEADER}\n{effect}\n"


def write_output(path: Path, content: str, newline: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = normalize_newlines(strip_trailing_whitespace(content), newline)
    path.write_text(content, encoding="utf-8-sig", newline="")


def main(inputs: RunInputs) -> None:
    assert_contains(
        read_source(inputs.CANON_CHILDREN_MODIFIERS),
        f"{CANON_CHILDREN_MODIFIER} = {{",
        "AGOT: Canon Children EZ Mode health boost modifier",
    )
    for name, path in inputs.DUEL_PHASE_EVENTS:
        assert_contains(
            extract(
                normalize_newlines(read_source(path), "\n"),
                "mfb_commander_duel_event",
            ),
            DUEL_COOLDOWN_GATE,
            f"{name} commander duel cooldown gate",
        )

    commander_raw = read_source(inputs.COMMANDER_PHASE_EVENTS)
    disaster_raw = read_source(inputs.NATURAL_DISASTER_EFFECTS)
    tournament_raw = read_source(inputs.TOURNAMENT_EFFECTS)

    write_output(
        inputs.COMMANDER_OUTPUT,
        build_commander_killed(normalize_newlines(commander_raw, "\n")),
        newline_style(commander_raw),
    )
    write_output(
        inputs.DISASTER_OUTPUT,
        build_natural_disaster(normalize_newlines(disaster_raw, "\n")),
        newline_style(disaster_raw),
    )
    write_output(
        inputs.TOURNAMENT_OUTPUT,
        build_tournament_accident(normalize_newlines(tournament_raw, "\n")),
        newline_style(tournament_raw),
    )
    print(
        "Generated canon enforcement: commander_killed, the natural disaster death "
        "roll and the tournament accident now skip protected characters; "
        "4 upstream markers asserted."
    )


def generate(context: GenerationContext) -> None:
    inputs = RunInputs(
        COMMANDER_PHASE_EVENTS=context.source("agot-commander-phase-events"),
        NATURAL_DISASTER_EFFECTS=context.source("agot-natural-disaster-effects"),
        TOURNAMENT_EFFECTS=context.source("agot-tournament-effects"),
        CANON_CHILDREN_MODIFIERS=context.source("canon-children-modifiers"),
        DUEL_PHASE_EVENTS=tuple((name, context.source(name)) for name in DUEL_SOURCES),
        COMMANDER_OUTPUT=context.output_path(
            "common/combat_phase_events/zzzz_agot_ce_commander_phase_events.txt"
        ),
        DISASTER_OUTPUT=context.output_path(
            "common/scripted_effects/zzzz_agot_ce_natural_disaster_effects.txt"
        ),
        TOURNAMENT_OUTPUT=context.output_path(
            "common/scripted_effects/zzzz_agot_ce_tournament_effects.txt"
        ),
    )
    main(inputs)
