#!/usr/bin/env python3
"""Generate the keyed redefinitions and the canon dragon taming fallback.

Two definitions live in `common/`, which resolves per key by ASCIIbetical
filename, so both are emitted into `zzzz_` files that win the key without
shadowing the neighbouring definitions their source files also carry.

The canon dragon outputs are additive instead. They read the dated
`agot_tame_dragon` entries in AGOT's dragon history — the only static record of
which rider bonded which dragon on which day — and emit a date-gated fallback
for the records AGOT's own tenth-birthday dispatch cannot reach.

The remaining sources are assertion-only: they pin the upstream markers this
module's runtime behaviour depends on, so a parent that renames or reworks one
fails generation instead of quietly disabling protection.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from gen import GenerationContext
from gen.data import csv_bytes
from gen.text import (
    definition_span,
    newline_style,
    normalize_newlines,
    read_source,
    replace_exact,
    strip_trailing_whitespace,
)

# The population gate in common/scripted_triggers/agot_ce_triggers.txt reads
# this modifier. If EZ Mode renames it, every protected character silently
# stops being protected.
CANON_CHILDREN_MODIFIER = "canon_children_easy_mode_health_boost_modifier"

# Holding this flag keeps the battlefield duel from being offered. Every mod
# that defines mfb_commander_duel_event gates its is_valid on the flag's
# absence; agot_ce_apply_protection_effect relies on all of them doing so.
DUEL_COOLDOWN_GATE = "NOT = { has_character_flag = mfb_duel_cooldown }"

DUEL_SOURCES = (
    "battle-events-phase-events",
    "battle-events-agot-phase-events",
    "duels-blademasters-phase-events",
)

COMMANDER_HEADER = """\
# Generated by workspace/agot_canon_enforcement. Redefines AGOT's commander_killed so
# a protected character cannot be picked as the commander who dies in a battle.
# Everything else about the event is AGOT's own. Must sort after every other
# combat_phase_events file, which is what the zzzz_ prefix buys.
"""

DISASTER_HEADER = """\
# Generated by workspace/agot_canon_enforcement. Redefines the natural disaster death
# roll so protected characters are never collected into killable_characters.
# The rest of the effect, including army damage and the player notifications,
# is unchanged. Must sort after every other scripted_effects file.
"""

COMMANDER_GATE = "\tis_valid = {\n\t\texists = root\n"
COMMANDER_GUARD = (
    "\tis_valid = {\n"
    "\t\texists = root\n"
    "\t\t#AGOT Canon Enforcement: protected characters are not eligible victims.\n"
    "\t\tagot_ce_battle_protected_trigger = no\n"
)

TOURNAMENT_HEADER = """\
# Generated by workspace/agot_canon_enforcement. Redefines the tournament
# accident death so a protected contestant survives the melee. The activity log
# entries and the reactions of the other attendees are unchanged. Must sort
# after every other scripted_effects file.
"""

# The two victim deaths in the accident effect, one with a killer and one
# without. Guarding the effect covers every event that calls it, which is what
# reaches both the melee accident and the tourney ground accident.
TOURNAMENT_DEATHS = (
    (
        "\t\t\tscope:accident_victim = {\n"
        "\t\t\t\tdeath = {\n"
        "\t\t\t\t\tdeath_reason = death_contest_melee_accident\n"
        "\t\t\t\t\tkiller = scope:accident_killer\n"
        "\t\t\t\t}\n"
        "\t\t\t}\n",
        "\t\t\tscope:accident_victim = {\n"
        "\t\t\t\tif = {\n"
        "\t\t\t\t\tlimit = { agot_ce_event_death_protected_trigger = no }\n"
        "\t\t\t\t\tdeath = {\n"
        "\t\t\t\t\t\tdeath_reason = death_contest_melee_accident\n"
        "\t\t\t\t\t\tkiller = scope:accident_killer\n"
        "\t\t\t\t\t}\n"
        "\t\t\t\t}\n"
        "\t\t\t}\n",
        "tournament accident death with a killer",
    ),
    (
        "\t\t\tscope:accident_victim = {\n"
        "\t\t\t\tdeath = { death_reason = death_contest_melee_accident }\n"
        "\t\t\t}\n",
        "\t\t\tscope:accident_victim = {\n"
        "\t\t\t\tif = {\n"
        "\t\t\t\t\tlimit = { agot_ce_event_death_protected_trigger = no }\n"
        "\t\t\t\t\tdeath = { death_reason = death_contest_melee_accident }\n"
        "\t\t\t\t}\n"
        "\t\t\t}\n",
        "tournament accident death without a killer",
    ),
)

DISASTER_COLLECT = (
    "\t\t\tevery_character_in_location = { add_to_list = killable_characters }\n"
)
DISASTER_GUARD = (
    "\t\t\tevery_character_in_location = {\n"
    "\t\t\t\t#AGOT Canon Enforcement: protected characters are not collected.\n"
    "\t\t\t\tlimit = { agot_ce_event_death_protected_trigger = no }\n"
    "\t\t\t\tadd_to_list = killable_characters\n"
    "\t\t\t}\n"
)


# --- Canon dragon tamings ---------------------------------------------------
#
# AGOT reaches a canon rider through two dispatch sites, both of which schedule
# dragon_taming_events.9000: on_10th_birthday_tame_canon_dragon, and a game
# start branch gated on `age >= 10`. Neither one has a retry, so a rider that
# passes neither gate never bonds. This module emits the date-gated fallback.

CANON_DRAGON_NAMESPACE = "agot_ce_canon_dragon"
CANON_DRAGON_EVENT = f"{CANON_DRAGON_NAMESPACE}.0001"

# AGOT's own canon dispatch. Both sites must keep scheduling event 9000 for the
# gap analysis below — and therefore the generated fallback — to stay true.
CANON_DISPATCH_EVENT = "dragon_taming_events.9000"
CANON_BIRTHDAY_ACTION = "on_10th_birthday_tame_canon_dragon"
CANON_GAME_START_AGE_GATE = "age >= 10"

# The effect the history records call, and the one the generated event calls
# through agot_ce_canon_dragon_bond_effect. Its two parameters are what makes
# a record replayable at runtime.
TAME_EFFECT = "agot_tame_dragon"
TAME_EFFECT_PARAMETERS = ("$TAMER$", "$DRAGON$")

# The dragonpit veto agot_ce_canon_dragon_bond_effect reuses verbatim.
PIT_TRIGGER = "agot_can_tame_or_bond_or_etc_with_pitted_dragons"
PIT_TRIGGER_PARAMETERS = ("$DRAGON$", "$ACTOR$")

# The global list both AGOT's event 9000 and the bond effect search.
LIVING_DRAGONS_LIST = "living_dragons"

# Riders AGOT creates after game start. A character created above age ten never
# sees on_10th_birthday, and was not alive for the game start sweep, so the
# canon dispatch never reaches them. Refresh the audit when this set changes.
EXPECTED_DYNAMIC_RIDERS = frozenset({"Farseed_1"})

# Riders whose is_<ID> flag no AGOT effect ever adds. agot_is_canon_rider and
# agot_is_canon_rider_dragon_pair both key on that flag, so event 9000 cannot
# fire for them at all; the generated branches identify them by character
# reference instead. Refresh the audit when this set changes.
EXPECTED_FLAGLESS_RIDERS = frozenset({"Belaerys_3", "Mataeryon_1", "Sonaryen_1"})

TRIGGER_HEADER = """\
# Generated by workspace/agot_canon_enforcement. One OR branch per dated
# agot_tame_dragon record in AGOT's dragon history: the rider's runtime
# identity, and the day the record says the bond was made. Additive; the key is
# this module's own.
"""

EVENT_HEADER = """\
# Generated by workspace/agot_canon_enforcement. Replays the canon rider-dragon
# bonds AGOT's tenth-birthday dispatch cannot reach, on the day each static
# history record gives. Every branch is a no-op unless the rider still has no
# dragon and the recorded dragon still has no rider.
"""

DATE_BLOCK = re.compile(r"^\s*(\d+)\.(\d+)\.(\d+)\s*=\s*\{")
TOP_BLOCK = re.compile(r"^([A-Za-z0-9_]+)\s*=\s*\{")
TAMER_LINE = re.compile(r"TAMER\s*=\s*character:([A-Za-z0-9_]+)")
BIRTH_LINE = re.compile(r"^\s*birth\s*=")
FLAG_LINE = re.compile(r"add_character_flag = (is_[A-Za-z0-9_]+)")
DRAGON_IDENTITY = re.compile(r"^(is_character_dragon_([A-Za-z0-9_]+)) = \{", re.M)


@dataclass(frozen=True, slots=True)
class TamingRecord:
    """One dated agot_tame_dragon entry, resolved to runtime identities."""

    rider: str
    dragon: str
    date: tuple[int, int, int]
    rider_flag: str | None
    dragon_token: str

    @property
    def date_text(self) -> str:
        return "{}.{}.{}".format(*self.date)

    @property
    def identity_lines(self) -> tuple[str, ...]:
        """How the generated script recognises this rider at runtime."""
        if self.rider_flag is not None:
            return (f"has_character_flag = {self.rider_flag}",)
        # Nothing adds this rider's canon flag, so fall back to the history
        # character itself. The existence guard mirrors AGOT's own pattern in
        # is_character_dragon_*, where a pruned character must not be compared.
        return (
            f"exists = character:{self.rider}",
            f"this = character:{self.rider}",
        )


def parse_taming_records(
    text: str,
) -> tuple[tuple[str, tuple[int, int, int], str], ...]:
    """Return (dragon, date, rider) for every dated agot_tame_dragon entry."""
    records: list[tuple[str, tuple[int, int, int], str]] = []
    dragon: str | None = None
    date: tuple[int, int, int] | None = None
    depth = 0
    for line in text.split("\n"):
        if depth == 0:
            top = TOP_BLOCK.match(line)
            if top:
                dragon = top.group(1)
                date = None
        if depth == 1:
            dated = DATE_BLOCK.match(line)
            if dated:
                date = (
                    int(dated.group(1)),
                    int(dated.group(2)),
                    int(dated.group(3)),
                )
        tamer = TAMER_LINE.search(line)
        if tamer:
            if dragon is None or date is None:
                raise ValueError(
                    f"dragon history: {TAME_EFFECT} outside a dated block: {line.strip()}"
                )
            records.append((dragon, date, tamer.group(1)))
        depth += line.count("{") - line.count("}")
    if not records:
        raise ValueError(f"dragon history: no dated {TAME_EFFECT} record found")
    return tuple(records)


def parse_birth_dates(paths: tuple[Path, ...]) -> dict[str, tuple[int, int, int]]:
    """Return each history character's first dated block that carries a birth."""
    births: dict[str, tuple[int, int, int]] = {}
    for path in paths:
        character: str | None = None
        date: tuple[int, int, int] | None = None
        depth = 0
        for line in normalize_newlines(read_source(path), "\n").split("\n"):
            if depth == 0:
                top = TOP_BLOCK.match(line)
                if top:
                    character = top.group(1)
                    date = None
            if depth == 1:
                dated = DATE_BLOCK.match(line)
                if dated:
                    date = (
                        int(dated.group(1)),
                        int(dated.group(2)),
                        int(dated.group(3)),
                    )
            if BIRTH_LINE.match(line) and character and date:
                births.setdefault(character, date)
            depth += line.count("{") - line.count("}")
    return births


def canon_rider_pairs(text: str) -> set[tuple[str, str]]:
    """Return the (rider flag, dragon token) pairs event 9000 can produce."""
    start, end = definition_span(text, "agot_is_canon_rider_dragon_pair", indent="")
    pairs: set[tuple[str, str]] = set()
    branches = re.split(r"\n\ttrigger_(?:if|else_if) = \{", text[start:end])
    for branch in branches[1:]:
        dragon = re.search(r"is_character_dragon_([A-Za-z0-9_]+) = yes", branch)
        if not dragon:
            raise ValueError(
                "agot_is_canon_rider_dragon_pair: branch without a dragon identity"
            )
        for flag in re.findall(r"has_character_flag = (is_[A-Za-z0-9_]+)", branch):
            pairs.add((flag.lower(), dragon.group(1).lower()))
    if not pairs:
        raise ValueError("agot_is_canon_rider_dragon_pair: no rider-dragon pair found")
    return pairs


def dragon_identity_tokens(text: str) -> dict[str, str]:
    """Map each dragon history key to the AGOT trigger that recognises it."""
    tokens: dict[str, str] = {}
    for match in DRAGON_IDENTITY.finditer(text):
        start, end = definition_span(text, match.group(1), indent="")
        body = text[start:end]
        reference = re.search(r"character:(dragon_[A-Za-z0-9_]+)", body)
        if reference:
            tokens[reference.group(1)] = match.group(2)
    if not tokens:
        raise ValueError("no is_character_dragon_* trigger names a history dragon")
    return tokens


def build_taming_records(
    dragon_history: str,
    canon_triggers: str,
    trait_triggers: str,
    init_effects: str,
    spawn_effects: str,
    *,
    expected_flagless: frozenset[str] = EXPECTED_FLAGLESS_RIDERS,
    expected_dynamic: frozenset[str] = EXPECTED_DYNAMIC_RIDERS,
) -> tuple[TamingRecord, ...]:
    """Resolve every history record to the identities the generated script uses."""
    flags = set(FLAG_LINE.findall(init_effects)) | set(FLAG_LINE.findall(spawn_effects))
    tokens = dragon_identity_tokens(trait_triggers)
    # Shape check only. Whether the pair trigger can reach a given record is
    # reported in the audit rather than enforced, because a record it omits is
    # exactly the kind of gap this module fills.
    canon_rider_pairs(canon_triggers)

    records: list[TamingRecord] = []
    seen: dict[str, str] = {}
    for dragon, date, rider in parse_taming_records(dragon_history):
        if rider in seen:
            raise ValueError(
                f"{rider} has more than one taming record ({seen[rider]} and {dragon}); "
                "a single if/else_if branch can no longer represent this rider"
            )
        seen[rider] = dragon
        if dragon not in tokens:
            raise ValueError(
                f"no is_character_dragon_* trigger references character:{dragon}, "
                "so the generated branch cannot identify the recorded dragon"
            )
        rider_flag = f"is_{rider}" if f"is_{rider}" in flags else None
        records.append(
            TamingRecord(
                rider=rider,
                dragon=dragon,
                date=date,
                rider_flag=rider_flag,
                dragon_token=tokens[dragon],
            )
        )

    flagless = {record.rider for record in records if record.rider_flag is None}
    if flagless != expected_flagless:
        raise ValueError(
            "the set of canon riders whose is_<ID> flag no effect adds changed "
            f"(now {sorted(flagless)}, pinned {sorted(expected_flagless)}); "
            "re-audit the fallback before regenerating"
        )
    spawn_flags = set(FLAG_LINE.findall(spawn_effects))
    dynamic = {record.rider for record in records if record.rider_flag in spawn_flags}
    if dynamic != expected_dynamic:
        raise ValueError(
            "the set of canon riders AGOT creates after game start changed "
            f"(now {sorted(dynamic)}, pinned {sorted(expected_dynamic)}); "
            "re-audit the fallback before regenerating"
        )

    records.sort(key=lambda record: (record.date, record.rider))
    return tuple(records)


def canon_taming_coverage(
    record: TamingRecord,
    births: dict[str, tuple[int, int, int]],
    spawn_flags: set[str],
    pairs: set[tuple[str, str]],
) -> tuple[str, str]:
    """Classify why AGOT's own dispatch does or does not reach this record."""
    if record.rider_flag is None:
        return "no_canon_flag", "agot_is_canon_rider never matches this rider"
    if record.rider_flag in spawn_flags:
        return "created_after_game_start", "created above age ten, so no tenth birthday"
    if (record.rider_flag.lower(), record.dragon_token.lower()) not in pairs:
        return "unpaired", f"{CANON_DISPATCH_EVENT} cannot select the recorded dragon"
    birth = births.get(record.rider)
    if birth is None:
        return "unknown_birth", "no birth entry in AGOT character history"
    age = record.date[0] - birth[0]
    if record.date[1:] < birth[1:]:
        age -= 1
    if age < 10:
        return "before_tenth_birthday", f"recorded at age {age}"
    return "birthday_dispatch", f"recorded at age {age}"


def build_canon_taming_trigger(records: tuple[TamingRecord, ...]) -> str:
    """Emit the OR over every record's runtime identity and its recorded day."""
    branches = []
    for record in records:
        lines = "\n".join(f"\t\t\t{line}" for line in record.identity_lines)
        branches.append(
            f"\t\tAND = {{ # {record.rider} and {record.dragon}\n"
            f"{lines}\n"
            f"\t\t\tcurrent_date >= {record.date_text}\n"
            "\t\t}"
        )
    body = "\n".join(branches)
    return (
        f"{TRIGGER_HEADER}\n"
        "agot_ce_canon_taming_due_trigger = {\n"
        "\tOR = {\n"
        f"{body}\n"
        "\t}\n"
        "}\n"
    )


def build_canon_taming_event(records: tuple[TamingRecord, ...]) -> str:
    """Emit the hidden dispatcher: one branch per record, exact dragon, exact day."""
    branches = []
    for index, record in enumerate(records):
        keyword = "if" if index == 0 else "else_if"
        lines = "\n".join(f"\t\t\t\t{line}" for line in record.identity_lines)
        branches.append(
            f"\t\t{keyword} = {{ # {record.rider} and {record.dragon}\n"
            "\t\t\tlimit = {\n"
            f"{lines}\n"
            f"\t\t\t\tcurrent_date >= {record.date_text}\n"
            "\t\t\t}\n"
            "\t\t\tagot_ce_canon_dragon_bond_effect = "
            f"{{ DRAGON = {record.dragon_token} }}\n"
            "\t\t}"
        )
    body = "\n".join(branches)
    return (
        f"{EVENT_HEADER}\n"
        f"namespace = {CANON_DRAGON_NAMESPACE}\n"
        "\n"
        f"{CANON_DRAGON_EVENT} = {{\n"
        "\tscope = character\n"
        "\thidden = yes\n"
        "\n"
        "\ttrigger = {\n"
        "\t\tagot_ce_canon_taming_pending_trigger = yes\n"
        "\t}\n"
        "\n"
        "\timmediate = {\n"
        f"{body}\n"
        "\t}\n"
        "}\n"
    )


def build_taming_audit(
    records: tuple[TamingRecord, ...],
    births: dict[str, tuple[int, int, int]],
    spawn_flags: set[str],
    pairs: set[tuple[str, str]],
) -> bytes:
    """Report every record and why AGOT's own dispatch does or does not reach it."""
    rows = []
    for record in records:
        coverage, reason = canon_taming_coverage(record, births, spawn_flags, pairs)
        birth = births.get(record.rider)
        rows.append(
            {
                "recorded_date": record.date_text,
                "rider": record.rider,
                "rider_birth": "{}.{}.{}".format(*birth) if birth else "",
                "rider_identity": record.rider_flag or f"character:{record.rider}",
                "dragon": record.dragon,
                "dragon_identity": f"is_character_dragon_{record.dragon_token}",
                "agot_coverage": coverage,
                "note": reason,
            }
        )
    return csv_bytes(
        [
            "recorded_date",
            "rider",
            "rider_birth",
            "rider_identity",
            "dragon",
            "dragon_identity",
            "agot_coverage",
            "note",
        ],
        rows,
    )


def extract(text: str, name: str) -> str:
    start, end = definition_span(text, name)
    return text[start:end]


def extract_top_level(text: str, name: str) -> str:
    """Extract a definition anchored at column zero.

    The dragon files call several of the definitions read here from inside
    other definitions, so the default indent-tolerant span would match more
    than one occurrence.
    """
    start, end = definition_span(text, name, indent="")
    return text[start:end]


def assert_contains(text: str, needle: str, label: str) -> None:
    if needle not in text:
        raise ValueError(f"{label}: expected to find `{needle}`, and it is gone")


def build_commander_killed(text: str) -> str:
    event = replace_exact(
        extract(text, "commander_killed"),
        COMMANDER_GATE,
        COMMANDER_GUARD,
        "commander_killed protected-character gate",
    )
    return f"{COMMANDER_HEADER}\n{event}\n"


def build_natural_disaster(text: str) -> str:
    effect = replace_exact(
        extract(text, "natural_disaster_death_damage_roll_effect"),
        DISASTER_COLLECT,
        DISASTER_GUARD,
        "natural disaster killable_characters collection",
    )
    return f"{DISASTER_HEADER}\n{effect}\n"


def build_tournament_accident(text: str) -> str:
    effect = extract(text, "tournament_accidental_death_effect")
    for old, new, label in TOURNAMENT_DEATHS:
        effect = replace_exact(effect, old, new, label)
    return f"{TOURNAMENT_HEADER}\n{effect}\n"


def write_output(path: Path, content: str, newline: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = normalize_newlines(strip_trailing_whitespace(content), newline)
    path.write_text(content, encoding="utf-8-sig", newline="")


def generate(context: GenerationContext) -> None:
    assert_contains(
        read_source(context.source("canon-children-modifiers")),
        f"{CANON_CHILDREN_MODIFIER} = {{",
        "AGOT: Canon Children EZ Mode health boost modifier",
    )
    for name in DUEL_SOURCES:
        path = context.source(name)
        assert_contains(
            extract(
                normalize_newlines(read_source(path), "\n"),
                "mfb_commander_duel_event",
            ),
            DUEL_COOLDOWN_GATE,
            f"{name} commander duel cooldown gate",
        )

    commander_raw = read_source(context.source("agot-commander-phase-events"))
    disaster_raw = read_source(context.source("agot-natural-disaster-effects"))
    tournament_raw = read_source(context.source("agot-tournament-effects"))

    write_output(
        context.output_path(
            "common/combat_phase_events/zzzz_agot_ce_commander_phase_events.txt"
        ),
        build_commander_killed(normalize_newlines(commander_raw, "\n")),
        newline_style(commander_raw),
    )
    write_output(
        context.output_path(
            "common/scripted_effects/zzzz_agot_ce_natural_disaster_effects.txt"
        ),
        build_natural_disaster(normalize_newlines(disaster_raw, "\n")),
        newline_style(disaster_raw),
    )
    write_output(
        context.output_path(
            "common/scripted_effects/zzzz_agot_ce_tournament_effects.txt"
        ),
        build_tournament_accident(normalize_newlines(tournament_raw, "\n")),
        newline_style(tournament_raw),
    )

    records = generate_canon_dragon_tamings(context)
    print(
        "Generated canon enforcement: commander_killed, the natural disaster death "
        "roll and the tournament accident now skip protected characters; "
        f"{len(records)} canon dragon taming records replayed on their recorded "
        "date; 10 upstream markers asserted."
    )


def assert_canon_dispatch_unchanged(context: GenerationContext) -> None:
    """Pin the AGOT behaviour the generated fallback is defined against."""
    tame_effect = extract_top_level(
        normalize_newlines(read_source(context.source("agot-dragon-effects")), "\n"),
        TAME_EFFECT,
    )
    for parameter in TAME_EFFECT_PARAMETERS:
        assert_contains(tame_effect, parameter, f"AGOT {TAME_EFFECT} parameters")

    pit_trigger = extract_top_level(
        normalize_newlines(read_source(context.source("agot-dragon-triggers")), "\n"),
        PIT_TRIGGER,
    )
    for parameter in PIT_TRIGGER_PARAMETERS:
        assert_contains(pit_trigger, parameter, f"AGOT {PIT_TRIGGER} parameters")

    dispatch = extract_top_level(
        normalize_newlines(
            read_source(context.source("agot-dragon-taming-events")), "\n"
        ),
        CANON_DISPATCH_EVENT,
    )
    for marker in (TAME_EFFECT, LIVING_DRAGONS_LIST, "agot_is_canon_rider_dragon_pair"):
        assert_contains(dispatch, marker, f"AGOT {CANON_DISPATCH_EVENT}")

    birthday = extract_top_level(
        normalize_newlines(
            read_source(context.source("agot-childhood-on-actions")), "\n"
        ),
        CANON_BIRTHDAY_ACTION,
    )
    assert_contains(birthday, CANON_DISPATCH_EVENT, f"AGOT {CANON_BIRTHDAY_ACTION}")

    game_start = normalize_newlines(
        read_source(context.source("agot-game-start-on-actions")), "\n"
    )
    start_dispatch = game_start.find(CANON_DISPATCH_EVENT)
    if start_dispatch < 0:
        raise ValueError(
            f"AGOT game start no longer dispatches {CANON_DISPATCH_EVENT}; "
            "the gap this module fills has changed"
        )
    if (
        CANON_GAME_START_AGE_GATE
        not in game_start[max(0, start_dispatch - 400) : start_dispatch]
    ):
        raise ValueError(
            f"AGOT's game start {CANON_DISPATCH_EVENT} dispatch no longer gates on "
            f"`{CANON_GAME_START_AGE_GATE}`; re-audit which riders it now reaches"
        )

    dragon_effects = normalize_newlines(
        read_source(context.source("agot-dragon-effects")), "\n"
    )
    assert_contains(
        extract_top_level(dragon_effects, "agot_dragons_on_start_effect"),
        f"name = {LIVING_DRAGONS_LIST}",
        "AGOT living dragon list initialization",
    )


def generate_canon_dragon_tamings(
    context: GenerationContext,
) -> tuple[TamingRecord, ...]:
    """Emit the date-gated fallback and its audit from AGOT's static records."""
    assert_canon_dispatch_unchanged(context)

    def source(path: Path) -> str:
        return normalize_newlines(read_source(path), "\n")

    spawn_effects = source(context.source("agot-historical-character-effects"))
    canon_triggers = source(context.source("agot-canon-dragon-triggers"))
    records = build_taming_records(
        source(context.source("agot-dragon-history")),
        canon_triggers,
        source(context.source("agot-canon-dragon-trait-triggers")),
        source(context.source("agot-character-init-effects")),
        spawn_effects,
    )

    write_output(
        context.output_path(
            "common/scripted_triggers/agot_ce_canon_dragon_triggers.txt"
        ),
        build_canon_taming_trigger(records),
        "\n",
    )
    write_output(
        context.output_path("events/agot_ce_canon_dragon_taming_events.txt"),
        build_canon_taming_event(records),
        "\n",
    )

    births = parse_birth_dates(
        tuple(sorted(context.source("agot-character-history").glob("*.txt")))
    )
    context.write_bytes(
        "artifacts/canon_dragon_tamings/taming_audit.csv",
        build_taming_audit(
            records,
            births,
            set(FLAG_LINE.findall(spawn_effects)),
            canon_rider_pairs(canon_triggers),
        ),
    )
    return records
