load_mod = {
	label = "AGOT"
	workshop_id = "2962333032"
}

load_mod = {
	label = "Grand Remembrance"
	workshop_id = "3678529052"
}

load_mod = {
	label = "Grand Remembrance AGOT"
	workshop_id = "3683507542"
}
