#!/usr/bin/env python3
"""Generate the landless-adventurer tweaks as key-level AGOT overrides."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from gen import GenerationContext
from gen.text import (
    definition_span,
    newline_style,
    normalize_newlines,
    read_source,
    replace_exact,
    strip_trailing_whitespace,
)

# Both AGOT occurrences of this gate are patch anchors. A third means AGOT
# gated another bastard decision and this module needs a re-audit.
EXPECTED_IS_LANDED = 2

LANDED_OR_ADVENTURER = """\
OR = {
			is_landed = yes
			is_landless_adventurer = yes
		}"""

BASTARD_HEADER = """\
# Generated by workspace/agot_adventurer_tweaks. Redefines the AGOT decisions
# agot_expose_my_true_parentage_decision and agot_royal_bastard_claim_decision
# so landless adventurers can use them. Must load after A Game of Thrones.
"""

EVICT_HEADER = """\
# Generated by workspace/agot_adventurer_tweaks. Redefines the AGOT interaction
# evict_adventurer_interaction so only the county's own county-tier holder can
# evict a camp. Must load after A Game of Thrones.
"""


@dataclass(frozen=True, slots=True)
class RunInputs:
    BASTARD_DECISIONS: Path
    LAAMP_INTERACTIONS: Path
    BASTARD_OUTPUT: Path
    EVICT_OUTPUT: Path


def extract(text: str, name: str) -> str:
    start, end = definition_span(text, name)
    return text[start:end]


def build_bastard_decisions(text: str) -> str:
    found = text.count("is_landed = yes")
    if found != EXPECTED_IS_LANDED:
        raise ValueError(
            "AGOT bastard decisions changed their landed gating: expected "
            f"{EXPECTED_IS_LANDED} `is_landed = yes` occurrence(s), found {found}"
        )

    expose = replace_exact(
        extract(text, "agot_expose_my_true_parentage_decision"),
        "\t\tis_adult = yes\n\t\tis_landed = yes\n",
        f"\t\tis_adult = yes\n\t\t{LANDED_OR_ADVENTURER}\n",
        "agot_expose_my_true_parentage_decision landed gate",
    )
    claim = replace_exact(
        extract(text, "agot_royal_bastard_claim_decision"),
        "\tis_valid = {\n\t\tis_landed = yes\n",
        f"\tis_valid = {{\n\t\t{LANDED_OR_ADVENTURER}\n",
        "agot_royal_bastard_claim_decision landed gate",
    )
    return f"{BASTARD_HEADER}\n{expose}\n\n{claim}\n"


def build_evict_interaction(text: str) -> str:
    evict = extract(text, "evict_adventurer_interaction")
    evict = replace_exact(
        evict,
        "\t\t\tis_at_war = no\n\t\t\tNOR = {\n",
        "\t\t\tis_at_war = no\n\t\t\thighest_held_title_tier = tier_county\n\t\t\tNOR = {\n",
        "evict_adventurer_interaction actor tier gate",
    )
    evict = replace_exact(
        evict,
        "\t\t\tdomicile.domicile_location.county.holder ?= {\n"
        "\t\t\t\ttarget_is_same_character_or_above = scope:actor\n"
        "\t\t\t}\n",
        "\t\t\tdomicile.domicile_location.county.holder ?= {\n"
        "\t\t\t\tthis = scope:actor\n"
        "\t\t\t}\n",
        "evict_adventurer_interaction direct-holder gate",
    )
    return f"{EVICT_HEADER}\n{evict}\n"


def write_output(path: Path, content: str, newline: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = normalize_newlines(strip_trailing_whitespace(content), newline)
    path.write_text(content, encoding="utf-8-sig", newline="")


def main(inputs: RunInputs) -> None:
    decisions_raw = read_source(inputs.BASTARD_DECISIONS)
    interactions_raw = read_source(inputs.LAAMP_INTERACTIONS)
    decisions = normalize_newlines(decisions_raw, "\n")
    interactions = normalize_newlines(interactions_raw, "\n")

    write_output(
        inputs.BASTARD_OUTPUT,
        build_bastard_decisions(decisions),
        newline_style(decisions_raw),
    )
    write_output(
        inputs.EVICT_OUTPUT,
        build_evict_interaction(interactions),
        newline_style(interactions_raw),
    )
    print(
        "Generated adventurer tweaks: 2 bastard decisions relaxed to "
        "landed-or-landless, 1 eviction interaction restricted to the county's "
        "own county-tier holder."
    )


def generate(context: GenerationContext) -> None:

    BASTARD_DECISIONS = context.source("agot-bastard-decisions")
    LAAMP_INTERACTIONS = context.source("agot-laamp-interactions")
    BASTARD_OUTPUT = context.output_path(
        "common/decisions/agot_decisions/zz_agot_adventurer_bastard_decisions.txt"
    )
    EVICT_OUTPUT = context.output_path(
        "common/character_interactions/zz_agot_adventurer_evict_interaction.txt"
    )
    inputs = RunInputs(
        BASTARD_DECISIONS=BASTARD_DECISIONS,
        LAAMP_INTERACTIONS=LAAMP_INTERACTIONS,
        BASTARD_OUTPUT=BASTARD_OUTPUT,
        EVICT_OUTPUT=EVICT_OUTPUT,
    )
    main(inputs)
