load_mod = {
	label = "AGOT"
	workshop_id = "2962333032"
}

load_mod = {
	label = "AGOT - Much Faster Activities"
	workshop_id = "3723597729"
}

load_mod = {
	label = "AGOT Canon Continuity"
	modfile = "../../mods/agot_canon_continuity/descriptor.mod"
}
