#!/usr/bin/env python3
"""Rebase CaFG onto AGOT's culture, faith, MAA, and event databases.

Two mechanisms, chosen per content type because CK3 resolves them differently:

* `common/` databases resolve per object, LIOS by ASCIIbetical filename. Every
  repair there is emitted as a `zzz_cafg_agot_*` keyed override carrying only
  the objects that actually change, so a CaFG edit to any neighbouring object
  is picked up instead of being silently reverted.
* `events/` resolve whole-file, same path only, and duplicate event ids are an
  engine error rather than an override. Those files are produced by a three-way
  merge with vanilla as the common ancestor of CaFG and AGOT.

Every removal, merge resolution, and post-merge marker count is asserted so a
CaFG or AGOT update fails loudly instead of drifting.
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from gen import GenerationContext
from gen.text import matching_brace, read_source, replace_exact


@dataclass(frozen=True, slots=True)
class RunInputs:
    MOD_SOURCE: Path
    SOURCE: Path
    MOD_OUTPUT: Path
    OUTPUT: Path
    AGOT_SOURCE: Path
    VANILLA_SOURCE: Path


KEYED_HEADER = (
    "# Generated by workspace/cafg_agot_compatch. Do not edit by hand.\n"
    "#\n"
    "# Keyed override of {source}.\n"
    "# `common/` resolves per object, LIOS by ASCIIbetical filename, so this file\n"
    "# redefines only the {count} object(s) AGOT's databases invalidate. Every other\n"
    "# object in the source file keeps CaFG's own definition.\n"
)


INVALID_MAA_TYPES = frozenset(
    [
        "abudrar",
        "archers_of_the_nile",
        "ayyar",
        "bondi",
        "bush_hunter",
        "cataphract",
        "druzhina",
        "emishi_horse_archers",
        "gakgung_archers",
        "garudas",
        "gendarme",
        "goedendag",
        "guinea_warrior",
        "horn_warrior",
        "huscarl",
        "hussar",
        "japanese_horse_archers",
        "khandayat",
        "mangudai",
        "maturkan_warriors",
        "metsanvartija",
        "monaspa",
        "mountaineer",
        "mubarizun",
        "mulaththamun",
        "palace_guards",
        "pesilat_warriors",
        "samurai",
        "sarawit",
        "schiltron",
        "shomer",
        "varangian_guards",
        "varangian_veterans",
        "vigmen",
        "zbrojnosh",
    ]
)

INVALID_TRADITIONS = frozenset(
    [
        "tradition_desert_nomads",
        "tradition_hidden_cities",
        "tradition_intensive_farming",
        "tradition_maritime_way_of_life",
        "tradition_saharan_nomads",
        "tradition_tgp_art_of_war",
        "tradition_tgp_barangay_confederations",
        "tradition_tgp_court_machinations",
        "tradition_tgp_fortified_strongholds",
        "tradition_tgp_hydraulic_builders",
        "tradition_tgp_mountain_island",
    ]
)

MAA_CALL = re.compile(
    r"E_kCAFG_generic_cultural_boon_MAA_gift\s*=\s*\{"
    r"[^\r\n]*\bMAA_TYPE\s*=\s*([A-Za-z0-9_]+)"
)
TRADITION_CHECK = re.compile(r"\bhas_cultural_tradition\s*=\s*([A-Za-z0-9_]+)")
WEIGHTED_BRANCH = re.compile(r"^        \d+\s*=\s*\{\s*(?:#.*)?$")
COASTAL_HELPER_CALL = "E_kCAFG_cultural_boon_tradition_fp1_coastal_warriors = yes"


def read_text(path: Path) -> str:
    return read_source(path, normalize_newlines=True)


def write_text(
    inputs: RunInputs, relative: str, text: str, *, root: Path | None = None
) -> None:
    path = (inputs.OUTPUT if root is None else root) / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8-sig", newline="\n")


def top_level_definitions(text: str) -> tuple[dict[str, str], list[str]]:
    """Split a `common/` database file into its column-zero definitions."""
    bodies: dict[str, str] = {}
    order: list[str] = []
    for match in re.finditer(r"(?m)^([A-Za-z0-9_]+)\s*=\s*\{", text):
        name = match.group(1)
        if name in bodies:
            raise RuntimeError(f"duplicate definition {name} in source file")
        opening = text.index("{", match.start())
        bodies[name] = text[match.start() : matching_brace(text, opening) + 1]
        order.append(name)
    return bodies, order


def keyed_override(
    source: str, rebased: str, expected: tuple[str, ...], relative: str
) -> str:
    """Emit only the definitions the rebase actually changed.

    Asserting the changed set means a CaFG release that edits one of these
    objects — or stops needing the repair — fails generation rather than being
    silently overridden by a stale copy.
    """
    source_bodies, order = top_level_definitions(source)
    rebased_bodies, _ = top_level_definitions(rebased)
    if set(source_bodies) != set(rebased_bodies):
        raise RuntimeError(
            f"{relative}: rebase added or removed top-level definitions: "
            f"{sorted(set(source_bodies) ^ set(rebased_bodies))}"
        )

    changed = tuple(
        name for name in order if source_bodies[name] != rebased_bodies[name]
    )
    if changed != expected:
        raise RuntimeError(
            f"{relative}: expected the rebase to change {list(expected)}, "
            f"changed {list(changed)}"
        )

    header = KEYED_HEADER.format(source=relative, count=len(changed))
    return header + "".join(f"\n{rebased_bodies[name]}\n" for name in changed)


CONFLICT = re.compile(
    r"(?ms)^<<<<<<< ours\n(?P<ours>.*?)"
    r"^\|\|\|\|\|\|\| base\n(?P<base>.*?)"
    r"^=======\n(?P<theirs>.*?)"
    r"^>>>>>>> theirs\n"
)


def merge_three_way(base: str, ours: str, theirs: str) -> str:
    """Merge CaFG and AGOT over their common vanilla ancestor.

    Both parents edit vanilla independently, so vanilla is the correct merge
    base: a hunk only conflicts where CaFG and AGOT changed the same vanilla
    lines, which is exactly the set a human has to rule on.
    """
    with tempfile.TemporaryDirectory() as directory:
        root = Path(directory)
        files = {"ours": ours, "base": base, "theirs": theirs}
        for name, text in files.items():
            (root / name).write_text(text, encoding="utf-8", newline="\n")
        result = subprocess.run(
            [
                "git",
                "merge-file",
                "--diff3",
                "-p",
                "-L",
                "ours",
                "-L",
                "base",
                "-L",
                "theirs",
                str(root / "ours"),
                str(root / "base"),
                str(root / "theirs"),
            ],
            capture_output=True,
            text=True,
        )
    if result.returncode < 0:
        raise RuntimeError(f"git merge-file failed: {result.stderr.strip()}")
    return result.stdout


def take_agot_disabled(ours: str, theirs: str, label: str) -> str:
    """Resolve a hunk AGOT disabled wholesale by commenting it out.

    CaFG only hooked into code AGOT no longer runs, so keeping CaFG's side
    would reintroduce an event chain AGOT deliberately removed.
    """
    if not ours.strip():
        raise RuntimeError(f"{label}: CaFG side is empty, resolution no longer applies")
    live = [
        line
        for line in theirs.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    if live:
        raise RuntimeError(
            f"{label}: AGOT no longer disables this block; "
            f"{len(live)} live line(s) remain, first: {live[0].strip()!r}"
        )
    return theirs


def combine_domain_conversion(ours: str, theirs: str, label: str) -> str:
    """Keep CaFG's granular conversion but convert to AGOT's chosen culture.

    AGOT retargets `stewardship_domain.1073` from the ruler's own culture to
    `scope:new_culture`. Taking either side alone loses one of the two changes.
    """
    if "set_county_culture = scope:new_culture" not in theirs:
        raise RuntimeError(f"{label}: AGOT no longer retargets to scope:new_culture")
    rebased = replace_exact(
        ours,
        "CULTURE = root.culture",
        "CULTURE = scope:new_culture",
        expected=1,
        label=label,
    )
    # Keep AGOT's own annotation and its commented-out original above the
    # replacement, so the merged file still records why the target changed.
    annotation = "".join(
        f"{line}\n" for line in theirs.splitlines() if line.lstrip().startswith("#")
    )
    return annotation + rebased


def maa_type(line: str) -> str | None:
    match = MAA_CALL.search(line)
    return match.group(1) if match else None


def script_brace_delta(line: str) -> int:
    """Count structural braces, excluding comments and quoted strings."""
    code = line.split("#", 1)[0]
    code = re.sub(r'"(?:\\.|[^"\\])*"', '""', code)
    return code.count("{") - code.count("}")


def weighted_branch(lines: list[str], marker: int) -> tuple[int, int]:
    start = next(
        (
            index
            for index in range(marker, -1, -1)
            if WEIGHTED_BRANCH.match(lines[index].rstrip("\r\n"))
        ),
        None,
    )
    if start is None:
        raise RuntimeError(
            f"CaFG cultural benefit at source line {marker + 1} "
            "has no enclosing weighted branch"
        )

    depth = 0
    for end in range(start, len(lines)):
        depth += script_brace_delta(lines[end])
        if depth == 0:
            if end < marker:
                break
            return start, end + 1
    raise RuntimeError(f"CaFG weighted branch at source line {start + 1} is unbalanced")


def generate_boons(inputs: RunInputs) -> None:
    relative = "common/scripted_effects/kei_cafg_cultural_boons_effects.txt"
    source = read_text(inputs.MOD_SOURCE / relative)
    lines = source.splitlines(keepends=True)
    removed = Counter()
    output: list[str] = []

    for line in lines:
        identifier = maa_type(line)
        if identifier in INVALID_MAA_TYPES:
            removed[identifier] += 1
            continue
        output.append(line)

    expected = {
        "bondi",
        "cataphract",
        "huscarl",
        "varangian_guards",
        "varangian_veterans",
        "vigmen",
    }
    if set(removed) != expected or sum(removed.values()) != 6:
        raise RuntimeError(
            "CaFG cultural-boon helpers: expected six removed MAA calls "
            f"for {sorted(expected)}, found {dict(removed)}"
        )

    text = "".join(output)
    text = replace_exact(
        text,
        """                random_list = {
                    150 = {}
                    50 = {
                        trigger = { NOT = { religion = religion:islam_religion } }
                        add_trait = pilgrim
                    }
                    50 = {
                        trigger = { religion = religion:islam_religion }
                        add_trait = hajjaj
                    }
                }""",
        "                add_trait = pilgrim",
        expected=1,
        label="CaFG AGOT pilgrimage trait",
    )
    text = replace_exact(
        text,
        """            if = {
                limit = { NOT = { knows_language_of_culture = culture:han } }
                learn_language_of_culture = culture:han
            }
            if = {
                limit = { NOT = { has_trait = confucian_education } }
                add_trait = confucian_education
            }
            add_trait_xp = {
                trait = confucian_education
                value = {
                    integer_range = {
                        min = small_lifestyle_random_xp_low
                        max = medium_lifestyle_random_xp_high
                    }
                }
            }
""",
        "",
        expected=1,
        label="CaFG AGOT scholar-official vanilla trait and language",
    )
    text = replace_exact(
        text,
        (
            'CONDITION = "OR = { terrain = plains terrain = steppe '
            'geographical_region = world_steppe }"'
        ),
        'CONDITION = "OR = { terrain = plains terrain = steppe }"',
        expected=1,
        label="CaFG AGOT pastoralist geographical region",
    )
    remaining_invalid = {
        identifier
        for identifier in MAA_CALL.findall(text)
        if identifier in INVALID_MAA_TYPES
    }
    if remaining_invalid:
        raise RuntimeError(
            "CaFG cultural-boon helpers still reference invalid MAA types: "
            f"{sorted(remaining_invalid)}"
        )
    write_text(
        inputs,
        "common/scripted_effects/zzz_cafg_agot_cultural_boons_effects.txt",
        keyed_override(
            source,
            text,
            (
                "E_kCAFG_cultural_boon_tradition_warrior_monks",
                "E_kCAFG_cultural_boon_tradition_pastoralists",
                "E_kCAFG_cultural_boon_tradition_fp1_coastal_warriors",
                "E_kCAFG_cultural_boon_tradition_ep3_imperial_tagmata",
                "E_kCAFG_cultural_boon_tradition_ep3_palace_politics",
                "E_kCAFG_cultural_boon_tradition_scholar_officials",
            ),
            relative,
        ),
        root=inputs.MOD_OUTPUT,
    )


def generate_benefits(inputs: RunInputs) -> None:
    relative = "common/scripted_effects/kei_cafg_cultural_benefits_effects.txt"
    source = read_text(inputs.MOD_SOURCE / relative)
    lines = source.splitlines(keepends=True)
    invalid_calls = Counter()
    markers: list[int] = []

    for index, line in enumerate(lines):
        identifier = maa_type(line)
        if identifier in INVALID_MAA_TYPES:
            invalid_calls[identifier] += 1
            markers.append(index)
        if any(
            tradition in INVALID_TRADITIONS
            for tradition in TRADITION_CHECK.findall(line)
        ):
            markers.append(index)

    if set(invalid_calls) != INVALID_MAA_TYPES - {
        "bondi",
        "cataphract",
        "varangian_guards",
        "varangian_veterans",
        "vigmen",
    }:
        raise RuntimeError(
            f"CaFG cultural-benefit invalid MAA set changed: {dict(invalid_calls)}"
        )
    if sum(invalid_calls.values()) != 30:
        raise RuntimeError(
            "CaFG cultural benefits: expected 30 invalid MAA calls, "
            f"found {sum(invalid_calls.values())}"
        )

    helper_markers = [
        index for index, line in enumerate(lines) if COASTAL_HELPER_CALL in line
    ]
    if len(helper_markers) != 1:
        raise RuntimeError(
            "CaFG coastal-warriors helper: expected one caller, found "
            f"{len(helper_markers)}"
        )
    markers.extend(helper_markers)

    if len(markers) != 42:
        raise RuntimeError(
            "CaFG cultural benefits: expected 42 invalid branch markers, "
            f"found {len(markers)}"
        )
    branches = {weighted_branch(lines, marker) for marker in markers}
    if len(branches) != 41:
        raise RuntimeError(
            "CaFG cultural benefits: expected 41 removed weighted branches, "
            f"found {len(branches)}"
        )

    for start, end in sorted(branches, reverse=True):
        del lines[start:end]

    text = "".join(lines)
    text = replace_exact(
        text,
        "\t\t\t\t\t\tgeographical_region = world_steppe\n",
        "",
        expected=1,
        label="CaFG AGOT pastoralist benefit geographical region",
    )
    remaining_invalid = {
        identifier
        for identifier in MAA_CALL.findall(text)
        if identifier in INVALID_MAA_TYPES
    }
    remaining_traditions = {
        tradition
        for tradition in TRADITION_CHECK.findall(text)
        if tradition in INVALID_TRADITIONS
    }
    if remaining_invalid or remaining_traditions or COASTAL_HELPER_CALL in text:
        raise RuntimeError(
            "CaFG cultural benefits retain an invalid database branch: "
            f"MAA={sorted(remaining_invalid)}, "
            f"traditions={sorted(remaining_traditions)}"
        )
    write_text(
        inputs,
        "common/scripted_effects/zzz_cafg_agot_cultural_benefits_effects.txt",
        keyed_override(source, text, ("E_kCAFG_apply_random_cultural_boon",), relative),
        root=inputs.MOD_OUTPUT,
    )


def generate_benefit_values(inputs: RunInputs) -> None:
    relative = "common/script_values/kei_cafg_cultural_benefits_values.txt"
    source = read_text(inputs.MOD_SOURCE / relative)
    text = source
    for tradition in ("tradition_cultural_primacy", "tradition_tgp_inward_perfection"):
        text = replace_exact(
            text,
            f"                has_cultural_tradition = {tradition}\n",
            "",
            expected=1,
            label=f"CaFG AGOT cultural benefit {tradition}",
        )
    text = replace_exact(
        text,
        """    if = {
        limit = {
            has_cultural_tradition = tradition_sinophilic
            scope:char.culture = { has_cultural_pillar = heritage_chinese }
        }
        multiply = 1.5
    }
""",
        "",
        expected=1,
        label="CaFG AGOT Sinophilic cultural benefit",
    )
    invalid = {
        "tradition_cultural_primacy",
        "tradition_tgp_inward_perfection",
        "tradition_sinophilic",
        "heritage_chinese",
    }
    remaining = sorted(identifier for identifier in invalid if identifier in text)
    if remaining:
        raise RuntimeError(
            f"CaFG cultural-benefit values retain AGOT-invalid identifiers: {remaining}"
        )
    write_text(
        inputs,
        "common/script_values/zzz_cafg_agot_cultural_benefits_values.txt",
        keyed_override(
            source, text, ("V_kCAFG_cultural_benefits_trigger_chance",), relative
        ),
        root=inputs.MOD_OUTPUT,
    )


def generate_tolerance_law_triggers(inputs: RunInputs) -> None:
    """Drop startup tolerance-law checks for AGOT's absent steppe tradition.

    AGOT replaces the culture database without `tradition_steppe_tolerance`, so
    each check fails `has_cultural_tradition` against a null target while CK3
    picks initial realm laws. Every surviving CaFG criterion is preserved.
    """
    cases = (
        (
            "culture",
            "            has_cultural_tradition = tradition_steppe_tolerance\n",
            (
                "T_kCAFG_should_start_with_intolerant_culture_law",
                "T_kCAFG_should_start_with_tolerant_culture_law",
            ),
        ),
        (
            "faith",
            "\t\tculture = { has_cultural_tradition = tradition_steppe_tolerance }\n",
            (
                "T_kCAFG_should_start_with_intolerant_faith_law",
                "T_kCAFG_should_start_with_tolerant_faith_law",
            ),
        ),
    )
    for kind, check, expected in cases:
        relative = f"common/scripted_triggers/kei_cafg_{kind}_laws_triggers.txt"
        source = read_text(inputs.MOD_SOURCE / relative)
        text = replace_exact(
            source,
            check,
            "",
            expected=2,
            label=f"CaFG AGOT {kind} tolerance-law steppe tradition",
        )
        if "tradition_steppe_tolerance" in text:
            raise RuntimeError(
                f"{relative} retains an AGOT-absent steppe-tolerance reference"
            )
        write_text(
            inputs,
            f"common/scripted_triggers/zzz_cafg_agot_{kind}_laws_triggers.txt",
            keyed_override(source, text, expected, relative),
            root=inputs.MOD_OUTPUT,
        )


@dataclass(frozen=True, slots=True)
class EventMerge:
    """One merged event file and the counts that keep the merge honest."""

    relative: str
    cafg_calls: int
    agot_markers: int
    resolutions: tuple[str, ...] = ()


AGOT_MARKER = re.compile(r"(?i)#\s*AGOT\b")
CAFG_CALL = re.compile(r"\bE_kCAFG_[A-Za-z0-9_]+")

EVENT_MERGES: tuple[EventMerge, ...] = (
    EventMerge(
        "events/activities/hold_court_activity/hold_court_events_general.txt",
        cafg_calls=1,
        agot_markers=62,
        resolutions=("agot_disabled",),
    ),
    EventMerge(
        "events/activities/tournaments/contest_events.txt",
        cafg_calls=1,
        agot_markers=24,
    ),
    EventMerge(
        "events/culture_events/culture_emergence_events.txt",
        cafg_calls=2,
        agot_markers=29,
    ),
    EventMerge(
        "events/decisions_events/ce1_decision_events.txt",
        cafg_calls=1,
        agot_markers=2,
    ),
    EventMerge(
        "events/dlc/bp2/bp2_yearly_events_6.txt",
        cafg_calls=2,
        agot_markers=12,
    ),
    EventMerge(
        "events/dlc/ce1/epidemic_events.txt",
        cafg_calls=1,
        agot_markers=49,
    ),
    EventMerge(
        "events/dlc/fp3/fp3_misc_decision_events.txt",
        cafg_calls=6,
        agot_markers=6,
    ),
    EventMerge(
        "events/global_religion_events.txt",
        cafg_calls=6,
        agot_markers=22,
        resolutions=("agot_disabled", "agot_disabled"),
    ),
    EventMerge(
        "events/lifestyles/governance_lifestyle/stewardship_domain_events.txt",
        cafg_calls=1,
        agot_markers=24,
        resolutions=("domain_conversion",),
    ),
    EventMerge(
        "events/religion_events/faith_conversion_events.txt",
        cafg_calls=1,
        agot_markers=9,
    ),
    EventMerge(
        "events/religion_events/false_conversion_events.txt",
        cafg_calls=3,
        agot_markers=2,
    ),
)

RESOLVERS = {
    "agot_disabled": take_agot_disabled,
    "domain_conversion": combine_domain_conversion,
}


def merge_event_file(inputs: RunInputs, merge: EventMerge, label: str = "AGOT") -> None:
    """Merge one CaFG event file onto the parent named by ``AGOT_SOURCE``.

    The LoV variant reuses this with LoV RC71 as the parent, so the merge
    strategy and conflict resolutions cannot drift between the two items.
    """
    base = read_text(inputs.VANILLA_SOURCE / merge.relative)
    ours = read_text(inputs.MOD_SOURCE / merge.relative)
    theirs = read_text(inputs.AGOT_SOURCE / merge.relative)
    merged = merge_three_way(base, ours, theirs)

    hunks = list(CONFLICT.finditer(merged))
    if len(hunks) != len(merge.resolutions):
        raise RuntimeError(
            f"{label} {merge.relative}: expected {len(merge.resolutions)} merge "
            f"conflict(s), found {len(hunks)}"
        )
    for index, hunk in reversed(list(enumerate(hunks))):
        name = merge.resolutions[index]
        hunk_label = f"{label} {merge.relative} hunk {index + 1} ({name})"
        resolved = RESOLVERS[name](hunk.group("ours"), hunk.group("theirs"), hunk_label)
        merged = merged[: hunk.start()] + resolved + merged[hunk.end() :]

    if "<<<<<<<" in merged or ">>>>>>>" in merged:
        raise RuntimeError(f"{label} {merge.relative}: unresolved conflict marker")

    calls = len(CAFG_CALL.findall(merged))
    markers = len(AGOT_MARKER.findall(merged))
    if (calls, markers) != (merge.cafg_calls, merge.agot_markers):
        raise RuntimeError(
            f"{label} {merge.relative}: expected {merge.cafg_calls} CaFG call(s) "
            f"and {merge.agot_markers} AGOT marker(s), merged output has "
            f"{calls} and {markers}"
        )
    write_text(inputs, merge.relative, merged, root=inputs.MOD_OUTPUT)


def generate_event_merges(inputs: RunInputs) -> None:
    """Rebuild every CaFG event hook on top of AGOT's current event files.

    `events/` override whole-file and same-path only — CK3 rejects a duplicate
    event id outright — so each of these files has to carry AGOT's complete
    text. Merging instead of hand-editing means an AGOT release lands here
    automatically, and the marker counts fail the build if it does not.
    """
    for merge in EVENT_MERGES:
        merge_event_file(inputs, merge)


COUNTY_VIEW = "gui/window_county_view.gui"
CAFG_GUI_TEMPLATES = "gui/kei_cafg_county_view_additions.gui"

COUNTY_VIEW_STATES_ANCHOR = "\talwaystransparent = yes\n\n\tvbox = {\n"
PROVINCE_BUTTONS_ANCHOR = (
    '\t\t\t\t\t\t\t\t\t\tvisible = "[HoldingView.HasSpecialBuildingSlot]"\n'
    "\t\t\t\t\t\t\t\t\t}\n"
    "\t\t\t\t\t\t\t\t}\n"
    "\t\t\t\t\t\t\t}\n"
    "\t\t\t\t\t\t}\n"
    "\t\t\t\t\t}\n"
    "\t\t\t\t}\n"
    "\t\t\t}\n"
)


def generate_county_view(inputs: RunInputs, source_root: Path, label: str) -> None:
    """Re-apply CaFG's two county-view hooks on top of another mod's window.

    `gui/window_*.gui` overrides whole-file and same-path only, so the compatch
    has to ship a complete copy. CaFG's entire delta is two `using` lines — the
    widgets themselves live in its own template file, which loads normally — so
    the copy is generated rather than hand-maintained.
    """
    for template in (
        "kCAFG_County_View_States",
        "kCAFG_Province_View_Additional_Buttons",
    ):
        defined = read_text(inputs.MOD_SOURCE / CAFG_GUI_TEMPLATES)
        if f"template {template}" not in defined:
            raise RuntimeError(
                f"CaFG no longer defines {template} in {CAFG_GUI_TEMPLATES}"
            )

    text = read_text(source_root / COUNTY_VIEW)
    text = replace_exact(
        text,
        COUNTY_VIEW_STATES_ANCHOR,
        "\talwaystransparent = yes\n\n"
        "\tusing = kCAFG_County_View_States\n\n"
        "\tvbox = {\n",
        expected=1,
        label=f"{label} county-view states anchor",
    )
    text = replace_exact(
        text,
        PROVINCE_BUTTONS_ANCHOR,
        PROVINCE_BUTTONS_ANCHOR.removesuffix("\t\t\t}\n")
        + "\t\t\tusing = kCAFG_Province_View_Additional_Buttons\n"
        + "\t\t\t}\n",
        expected=1,
        label=f"{label} province-view buttons anchor",
    )
    write_text(inputs, COUNTY_VIEW, text, root=inputs.MOD_OUTPUT)


DISABLED_VANILLA_FILES: tuple[tuple[str, tuple[str, ...], str], ...] = (
    (
        "common/casus_belli_types/99_kei_cafg_replaced_fp3_wars.txt",
        ("fp3_zanj_rebellion_war",),
        "CaFG's replacement defines the vanilla Zanj rebellion casus belli.\n"
        "AGOT removes the war, its faiths, and its script values.",
    ),
    (
        "common/decisions/99_kei_cafg_replaced_major_decisions_middle_east.txt",
        ("embrace_outremer_culture_decision",),
        "CaFG's replacement defines the vanilla Outremer culture decision. AGOT\n"
        "has neither the vanilla Outremer titles and regions nor its\n"
        "Catholic/Arabic culture setup, so merely evaluating the decision\n"
        "produces repeated invalid faith, culture, title, and\n"
        "geographical-region scopes.",
    ),
    (
        "common/decisions/dlc_decisions/fp_3/99_kei_cafg_replaced_fp3_decisions.txt",
        ("adopt_a_new_faith_for_persia_decision",),
        "CaFG's replacement defines the vanilla Persian Struggle\n"
        "faith-conversion decision. AGOT removes the Persian Struggle, Islam,\n"
        "its vanilla faiths, and the associated head-of-faith titles, so\n"
        "evaluating the decision continuously produces invalid database scopes.",
    ),
    (
        "common/scripted_effects/99_kei_cafg_replaced_decisions_effects.txt",
        (
            "reclaim_britannia_decision_effect",
            "embrace_english_culture_effect",
            "form_portugal_decision_effects",
            "unite_africa_decision_effects",
            "avenge_the_battle_of_tours_decision_effects",
            "become_saoshyant_decision_effect",
            "launch_hungarian_migration_scripted_effect",
        ),
        "CaFG's replacement defines seven vanilla regional decision effects.\n"
        "AGOT removes the decisions, titles, and cultures they operate on.",
    ),
    (
        "common/scripted_effects/99_kei_cafg_replaced_dlc_fp3_scripted_effects.txt",
        (
            "avenge_the_battle_of_nahrawan_scripted_effect",
            "fp3_ending_effects_assertion",
            "fp3_struggle_ending_shia_caliphate_effects",
            "fp3_struggle_ending_vassalize_caliph_effects",
            "fp3_struggle_rekindle_iran_effects",
        ),
        "CaFG's replacement defines five vanilla Persian-Struggle effects.\n"
        "AGOT removes the struggle itself along with its faiths and titles.",
    ),
)


def generate_disabled_vanilla_overrides(inputs: RunInputs) -> None:
    """Blank CaFG files that reintroduce vanilla-only content AGOT disables.

    A single-object `common/` override can redefine an object but never remove
    one, and CK3 still parses the original file either way. An exact-path,
    intentionally empty override is the only mechanism that stops these
    definitions loading at all.
    """
    for relative, definitions, reason in DISABLED_VANILLA_FILES:
        source = read_text(inputs.MOD_SOURCE / relative)
        for definition in definitions:
            found = source.count(f"{definition} = {{")
            if found != 1:
                raise RuntimeError(
                    f"CaFG vanilla-only override {relative}: expected one "
                    f"{definition} definition, found {found}"
                )
        body = "".join(f"# {line}\n".rstrip(" ") for line in reason.split("\n"))
        write_text(
            inputs,
            relative,
            "# AGOT compatibility: intentionally empty.\n#\n" + body,
            root=inputs.MOD_OUTPUT,
        )


def main(inputs: RunInputs) -> None:
    generate_boons(inputs)
    generate_benefits(inputs)
    generate_benefit_values(inputs)
    generate_tolerance_law_triggers(inputs)
    generate_disabled_vanilla_overrides(inputs)
    generate_event_merges(inputs)
    generate_county_view(inputs, inputs.AGOT_SOURCE, "AGOT")
    print(
        "Generated CaFG/AGOT rebase: 5 keyed common/ overrides "
        "(35 removed MAA types, 11 removed traditions, 4 runtime identifiers, "
        f"4 steppe-tolerance checks), {len(DISABLED_VANILLA_FILES)} vanilla-only "
        f"files disabled, {len(EVENT_MERGES)} event files merged."
    )


def generate(context: GenerationContext) -> None:

    MOD_SOURCE = context.source("culture-faith-granularity")
    SOURCE = MOD_SOURCE / "common/scripted_effects"
    MOD_OUTPUT = context.output_root
    OUTPUT = MOD_OUTPUT / "common/scripted_effects"
    inputs = RunInputs(
        MOD_SOURCE=MOD_SOURCE,
        SOURCE=SOURCE,
        MOD_OUTPUT=MOD_OUTPUT,
        OUTPUT=OUTPUT,
        AGOT_SOURCE=context.source("a-game-of-thrones"),
        VANILLA_SOURCE=context.source("vanilla"),
    )
    main(inputs)
