load_mod = {
	label = "AGOT"
	workshop_id = "2962333032"
}
load_mod = {
	label = "AGOT More Dragon Eggs"
	workshop_id = "3388366564"
}
load_mod = {
	label = "Immersive Personalities"
	workshop_id = "3596393244"
}
load_mod = {
	label = "COW"
	workshop_id = "2971198450"
}
load_mod = {
	label = "Mari's AGOT Makeovers"
	workshop_id = "3462342647"
}
load_mod = {
	label = "AGOT Seasons of Ice and Fire"
	workshop_id = "3377641022"
}
load_mod = {
	label = "Battle Graphics"
	workshop_id = "3225355262"
}
load_mod = {
	label = "Battle Graphics AGOT Compatibility Patch"
	workshop_id = "3235061780"
}
load_mod = {
	label = "Faster Transitions"
	workshop_id = "3437814875"
}
load_mod = {
	label = "A Landed Knights Mod"
	workshop_id = "3361162762"
}
load_mod = {
	label = "Expanded Court Position"
	workshop_id = "3676293022"
}
load_mod = {
	label = "Legitimacy Over Time"
	workshop_id = "3305687550"
}
load_mod = {
	label = "The Red Keep Hegemony Updates"
	workshop_id = "3662281614"
}
load_mod = {
	label = "Automated Squire Training"
	workshop_id = "3674548216"
}
load_mod = {
	label = "AGOT The Knighting Ceremony"
	workshop_id = "3673468355"
}
load_mod = {
	label = "AGOT House Founders"
	workshop_id = "2967263410"
}
load_mod = {
	label = "Succession Crisis"
	workshop_id = "3713902872"
}
load_mod = {
	label = "More Interactive Vassals"
	workshop_id = "2712590542"
}
load_mod = {
	label = "Any New Traditions"
	workshop_id = "3241130652"
}
load_mod = {
	label = "Any New Traditions Compatibility AGOT"
	workshop_id = "3371298408"
}
load_mod = {
	label = "AGOT Great Councils"
	workshop_id = "3621472324"
}
load_mod = {
	label = "AGOT Suggest Dragon Bonding"
	workshop_id = "3324579171"
}
load_mod = {
	label = "Adventurer's Beneficiary"
	workshop_id = "3349316031"
}
load_mod = {
	label = "AGOT: All Men Must Serve"
	workshop_id = "3761342990"
}
load_mod = {
	label = "Deadly CK3 AGOT"
	workshop_id = "3445965581"
}
load_mod = {
	label = "Artifact Manager"
	workshop_id = "2886417277"
}
load_mod = {
	label = "Advanced Character Search"
	workshop_id = "3084203091"
}
load_mod = {
	label = "Upgrade House Banners 3"
	workshop_id = "3709868073"
}
load_mod = {
	label = "AGOT Additional Models"
	workshop_id = "3319354609"
}
load_mod = {
	label = "Legacy of Valyria"
	workshop_id = "3403938445"
}
load_mod = {
	label = "Legacy of Valyria AGOT temporary compatch"
	workshop_id = "3719888822"
}
load_mod = {
	label = "Additional Models/AGOT+/LoV compatch"
	workshop_id = "3762892081"
}
load_mod = {
	label = "Essos Expanded"
	workshop_id = "3682802751"
}
load_mod = {
	label = "Essos Expanded LoV history rebase"
	modfile = "../../mods/essos_expanded_119_rebase/descriptor.mod"
}
load_mod = {
	label = "Essos Expanded LoV"
	workshop_id = "3768149491"
}
load_mod = {
	label = "Better AI Education & Ward Limit BOL"
	workshop_id = "3732116186"
}
load_mod = {
	label = "Character UI Overhaul"
	workshop_id = "2519175282"
}
