[generator]
entrypoint = "map_merge.py:generate"
owned_outputs = [
  "gfx/map",
  "map_data/definition.csv",
  "map_data/default.map",
  "map_data/provinces.png",
  "common/landed_titles/01_agot_landed_titles.txt",
  "common/landed_titles/lv_rhoyne_titles.txt",
  "common/landed_titles/lv_volantis_titles.txt",
  "common/landed_titles/01_landed_titles.txt",
  "history/titles/lv_development_levels.txt",
  "history/titles/zz_eetlv_cob_dejure.txt",
  "history/provinces/zz_agot_new_region_prov.txt",
]
owned_artifacts = [
  "heightmap",
  "map_objects",
  "map_data",
]

[[sources]]
name = "agot"
kind = "workshop"
item_id = "2962333032"

[[sources]]
name = "now"
kind = "workshop"
item_id = "3664900993"

[[sources]]
name = "lov"
kind = "workshop"
item_id = "3403938445"

[[sources]]
name = "lov-bridge"
kind = "workshop"
item_id = "3719888822"

[[sources]]
name = "essos-expanded"
kind = "workshop"
item_id = "3682802751"

[[sources]]
name = "essos-bridge"
kind = "workshop"
item_id = "3768149491"
