[generator]
entrypoint = "map_merge.py:generate"
owned_outputs = [
  "gfx/map/map_object_data",
  "map_data",
]
owned_artifacts = [
  "map_data",
]

[[sources]]
name = "agot"
kind = "workshop"
item_id = "2962333032"

[[sources]]
name = "now"
kind = "workshop"
item_id = "3664900993"

[[sources]]
name = "essos-expanded"
kind = "workshop"
item_id = "3682802751"

[[sources]]
name = "essos-bridge"
kind = "workshop"
item_id = "3768149491"

[[sources]]
name = "essos-compatch"
kind = "workshop"
item_id = "3773608127"
