load_mod = {
	label = "AGOT"
	workshop_id = "2962333032"
}

load_mod = {
	label = "AGOT Dragon Wives"
	workshop_id = "3541596590"
}

load_mod = {
	label = "AGOT - More Personality Depth"
	workshop_id = "3717990443"
}

load_mod = {
	label = "AGOT MPD runtime rebase"
	modfile = "../agot_mpd_119_rebase/descriptor.mod"
}
