#!/usr/bin/env python3
"""Generate the Inner Circle court position revoke-cost overrides."""

from __future__ import annotations

from gen import GenerationContext
from gen.text import (
    definition_span,
    newline_style,
    normalize_newlines,
    read_source,
    replace_exact,
    strip_trailing_whitespace,
)

# Every court position that charges prestige on dismissal and carries no Inner
# Circle check of its own reaches its cost through one of these three shared
# values. `medium` is defined but unreferenced today; it is carried so a
# position that later adopts it is covered without a second pass.
REVOKE_COSTS = {
    "minor_court_position_prestige_revoke_cost": 25,
    "medium_court_position_prestige_revoke_cost": 75,
    "major_court_position_prestige_revoke_cost": 200,
}

# AGOT's own body, reproduced verbatim. It is both the anchor the Inner Circle
# clause is appended after and the assertion that the pinned value is still the
# one being patched.
COST_REMOVAL_CLAUSE = """\
\tif = {
\t\tlimit = {
\t\t\texists = this
\t\t\thas_character_flag = temporary_court_position_cost_removal
\t\t}
\t\tmultiply = 0
\t}
"""

# `revoke_cost` is evaluated with root = liege and no employee scope, so the
# holder being dismissed cannot be identified from a shared script value. The
# gate is therefore "a house member holds a court position" rather than "the
# holder being dismissed is a house member". `exists = this` mirrors AGOT's own
# guard for the scopeless UI evaluation; `exists = dynasty` with
# `house = prev.house` is vanilla's house test from `00_camp_officers.txt`.
INNER_CIRCLE_CLAUSE = """\
\t# fp2_coterie_legacy_1 - house members are dismissed without a prestige cost.
\tif = {
\t\tlimit = {
\t\t\texists = this
\t\t\tdynasty ?= { has_dynasty_perk = fp2_coterie_legacy_1 }
\t\t\tany_court_position_holder = {
\t\t\t\texists = dynasty
\t\t\t\thouse = prev.house
\t\t\t}
\t\t}
\t\tmultiply = {
\t\t\tvalue = 0
\t\t\tdesc = inner_circle_salary_mod
\t\t}
\t}
"""

HEADER = """\
# Generated by workspace/agot_inner_circle_revoke_cost. Redefines only the three
# shared court position prestige revoke costs so the Inner Circle dynasty perk
# delivers the free dismissal its description promises. Must load after A Game of
# Thrones.
"""


def expected_definition(name: str, value: int) -> str:
    """Return the AGOT body this override is pinned to."""
    return f"{name} = {{\n\tvalue = {value}\n{COST_REMOVAL_CLAUSE}}}"


def build_revoke_cost(source: str, name: str, value: int) -> str:
    """Append the Inner Circle clause to one shared revoke cost."""
    start, end = definition_span(source, name)
    definition = source[start:end]
    if definition != expected_definition(name, value):
        raise ValueError(
            f"{name}: AGOT no longer defines this value as the pinned "
            f"`value = {value}` body; re-audit the override before regenerating"
        )
    return replace_exact(
        definition,
        COST_REMOVAL_CLAUSE,
        f"{COST_REMOVAL_CLAUSE}{INNER_CIRCLE_CLAUSE}",
        f"{name} temporary_court_position_cost_removal clause",
    )


def generate(context: GenerationContext) -> None:
    source_path = context.source("agot-court-position-values")
    output_path = context.output_path(
        "common/script_values/zz_agot_inner_circle_revoke_cost.txt"
    )

    source_raw = read_source(source_path)
    source = normalize_newlines(source_raw, "\n")

    definitions = [
        build_revoke_cost(source, name, value) for name, value in REVOKE_COSTS.items()
    ]
    output = f"{HEADER}\n" + "\n\n".join(definitions) + "\n"
    output = normalize_newlines(
        strip_trailing_whitespace(output), newline_style(source_raw)
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8-sig", newline="")
    print(
        "Generated "
        + ", ".join(f"{name} ({value})" for name, value in REVOKE_COSTS.items())
        + " with the fp2_coterie_legacy_1 clause."
    )
