load_mod = {
	label = "AGOT"
	workshop_id = "2962333032"
}
load_mod = {
	label = "NOW"
	workshop_id = "3664900993"
}
load_mod = {
	label = "NOW CK3 1.19 rebase"
	modfile = "../../agot_now_119_rebase/descriptor.mod"
}
load_mod = {
	label = "LoV"
	workshop_id = "3403938445"
}
load_mod = {
	label = "LoV AGOT 0.4.39 RC71"
	workshop_id = "3719888822"
}
load_mod = {
	label = "LoV RC71 CK3 1.19 runtime rebase"
	modfile = "../../legacy_of_valyria_039_runtime_rebase/descriptor.mod"
}
load_mod = {
	label = "Essos Expanded"
	workshop_id = "3682802751"
}
load_mod = {
	label = "Essos Expanded LoV history rebase"
	modfile = "../../essos_expanded_119_rebase/descriptor.mod"
}
load_mod = {
	label = "Essos Expanded LoV"
	workshop_id = "3768149491"
}
load_mod = {
	label = "AGOT NOW-Season of Ice and Fire Compatch"
	workshop_id = "3753608966"
}
load_mod = {
	label = "Seasons of Valyria TempLoV/NOW/Seasons Compatch"
	workshop_id = "3766038754"
}
load_mod = {
	label = "Essos Expanded TempLoV/NOW Compatch"
	workshop_id = "3773608127"
}
