[generator]
entrypoint = "implementation.py:generate"
owned_outputs = [
  "common",
  "events",
  "gfx",
  "gui",
  "history",
  "localization",
  "music",
  "thumbnail.png",
]

[[sources]]
name = "agot"
kind = "workshop"
item_id = "2962333032"

[[sources]]
name = "submod-core"
kind = "workshop"
item_id = "3034473189"

[[sources]]
name = "seasons"
kind = "workshop"
item_id = "3377641022"

[[sources]]
name = "long-night"
kind = "workshop"
item_id = "3766462389"
